version: '3'
services:
  app1:
    build:
      context: .
      dockerfile: ./cmd/helloworld/Dockerfile
    ports:
      - "8082:80"
    environment:
      WEBBODY: "Container 1"

  app2:
    build:
      context: .
      dockerfile: ./cmd/helloworld/Dockerfile
    ports:
      - "8083:80"
    environment:
      WEBBODY: "Container 2"
